site_name: IEEE Hyderabad
site_description: 'IEEE Hyderabad Section. IEEE,Hyderabad,Computers,Communication,Signal Procesing,MTT,AP,EMC,Power Engieering,PES,PELS,IAS,CIS,GRSS,Vizag,Guntur,Anathapuram,Students'
theme:
    name: mkdocs
    custom_dir: ieeehyd_theme
extra_css: [extra.css]
google_analytics: ['UA-111776382-1', 'ieeehyderabad.org']
markdown_extensions:
    - smarty

pages:
  - 'Home': 'index.md'
  - 'Section': 'section/section.md'
  - 'Chapters/AG':
          - 'Computer Society': 'chapters/cs/computers.md'
          - 'PES/IAS/PELS': 'chapters/pes-ias-pels/pes-ias-pels.md'
          - 'MTT/AP/EMC': 'chapters/mtt-ap-emc/mtt-ap-emc.md'
          - 'ComSoc/SP': 'chapters/comsoc-sp/comsoc-sp.md'
          - 'CIS/GRSS': 'chapters/cis-grss/cis-grss.md'
          - 'Education Society': 'chapters/edusoc/edusoc.md'
          - 'Photonics': 'chapters/photonics/photonics.md'
          - 'TEMS': 'chapters/tems/tems.md'
          - 'CAS/EDS': 'chapters/cas-eds/cas-eds.md'
          - 'Women in Engineering (WiE)': 'affinity-groups/wie/wie.md'
          - 'Young Professionals (YP)': 'affinity-groups/yp/yp.md'
  - 'Sub-Sections': 
          - 'Vizag Bay': 'sub-sections/vizag/vizag.md'
          - 'Guntur (Amaravathi)': 'sub-sections/guntur/guntur.md'
          - 'Ananthapur': 'sub-sections/ananthapur/ananthapur.md'
  - 'Students': 'students/students.md'
  - 'Newsletters': 'section/newsletters/details.md'
  - 'More...':
      - 'Upcoming Events': 'more/announcements/upcoming-events/upcoming-events.md'
      - 'Get Involved': 'section/get-involved/volunteering.md'
      - 'FAQ': 'support/faq/faq.md'
      - 'Content Instructions': 'support/faq/content-template.md'
      - 'Contact': 'support/contact/ieeehyderabad.md'

