site_name: IEEE Hyderabad
site_description: 'IEEE Hyderabad Section. IEEE,Hyderabad,Computers,Communication,Signal Procesing,MTT,AP,EMC,Power Engieering,PES,PELS,IAS,CIS,GRSS,Vizag,Guntur,Anathapuram,Students'
theme:
    name: mkdocs
    custom_dir: ieeehyd_theme
extra_css: [extra.css]
google_analytics: ['UA-111776382-1', 'ieeehyderabad.org']
markdown_extensions:
    - smarty

pages:
    - 'Home': 'index.md'

    - 'Section': 
                - 'IEEE Hyderabad Section': 'section/section.md'
                - 'Future Directions Committee': 'section/future-directions/2018.md'
                - 'Newsletters': 'section/newsletters/details.md'
                - 'Contact': 'support/contact/ieeehyderabad.md'
    - 'Sub-Sections': 
                - 'Vizag Bay': 'sub-sections/vizag/vizag.md'
                - 'Guntur (Amaravathi)': 'sub-sections/guntur/guntur.md'
                - 'Ananthapur': 'sub-sections/ananthapur/ananthapur.md'
    - 'Flagship Events':
                - 'Conferences': 'section/flagship-programs/conferences/conferences.md'
                - 'Faraday Memorial Lecture (FML)': 'section/flagship-programs/fml/fml.md'
                - 'Section Student Congress (SSC)': 'section/flagship-programs/section-student-congress/ssc.md'
                - 'SIGHT': 'section/flagship-programs/sight/sight.md'
                - 'Skill Connect': 'section/flagship-programs/skill-connect/skill-connect.md'
                - 'CAS/EDS': 'chapters/cas-eds/flagship-programs/details.md'
                - 'CIS/GRSS': 'chapters/cis-grss/flagship-programs/details.md'
                - 'Computer Society': 'chapters/cs/flagship-programs/details.md'
                - 'ComSoc/SP': 'chapters/comsoc-sp/flagship-programs/details.md'
                - 'Education Society': 'chapters/edusoc/flagship-programs/details.md'
                - 'MTT/AP/EMC': 'chapters/mtt-ap-emc/flagship-programs/details.md'
                - 'PES/IAS/PELS': 'chapters/pes-ias-pels/flagship-programs/details.md'
                - 'Photonics': 'chapters/photonics/flagship-programs/details.md'
                - 'TEMS': 'chapters/tems/flagship-programs/details.md'
                - 'Women in Engineering (WiE)': 'affinity-groups/wie/flagship-programs/details.md'
                - 'Young Professionals (YP)': 'affinity-groups/yp/flagship-programs/details.md'
                
    - 'Chapters/AG':
                - 'CAS/EDS': 'chapters/cas-eds/cas-eds.md'
                - 'CIS/GRSS': 'chapters/cis-grss/cis-grss.md'
                - 'Computer Society': 'chapters/cs/computers.md'
                - 'ComSoc/SP': 'chapters/comsoc-sp/comsoc-sp.md'
                - 'Education Society': 'chapters/edusoc/edusoc.md'
                - 'MTT/AP/EMC': 'chapters/mtt-ap-emc/mtt-ap-emc.md'
                - 'PES/IAS/PELS': 'chapters/pes-ias-pels/pes-ias-pels.md'
                - 'Photonics': 'chapters/photonics/photonics.md'
                - 'TEMS': 'chapters/tems/tems.md'
                - 'Women in Engineering (WiE)': 'affinity-groups/wie/wie.md'
                - 'Young Professionals (YP)': 'affinity-groups/yp/yp.md'

    - 'Students':
                - 'Activites': 'students/students.md'
                - 'Student Branches': 'students/branches/sbs.md'

    - 'More...':
        - 'Newsletters': 'section/newsletters/details.md'
        - 'Upcoming Events': 'more/announcements/upcoming-events/upcoming-events.md'
        - 'Get Involved': 'section/get-involved/volunteering.md'
        - 'FAQ': 'support/faq/faq.md'
        - 'Content Instructions': 'support/faq/content-template.md'
        - 'Contact': 'support/contact/ieeehyderabad.md'

