site_name: IEEE Hyderabad
google_analytics: ['UA-111776382-1', 'ieeehyderabad.org']
markdown_extensions:
    - smarty
pages:
  - 'Home': 'index.md'
  - 'Section':
      - 'Execom':
          - 'Execom 2018': 'execom/2018/slate-2018.md'
          - 'Execom 2017': 'execom/2017/slate-2017.md'
      - 'Sub-Sections': 
          - 'Vizag Bay': 'sub-sections/vizag/vizag.md'
          - 'Guntur (Amaravathi)': 'sub-sections/guntur/guntur.md'
          - 'Ananthapur': 'sub-sections/ananthapur/ananthapur.md'
      - 'Programs':
          - 'Conferences': 'conferences/conferences.md'
          - 'Faraday Memorial Lecture (FML)': 'fml/fml.md'
          - 'Section Student Congress (SSC)': 'students/section-student-congress/ssc.md'
          - 'SIGHT': 'sight/sight.md'
          - 'Skill Connect': 'skill-connect/skill-connect.md'
      - 'Finances':
          - 'Current Year Finances (2017-2018)': 'finances/finances.md'
          - 'AGM 2018': 'agm/2018/agm-2018.md'
          - 'AGM 2017': 'agm/2017/agm-2017.md'
          - 'SAGM 2017': 'sagm/sagm-2017.md'
      - 'SEC Proceedings':
          - 'SEC Proceedings 2018': 
              - 'January': 'sec-proceedings/2018/january.md'
      - 'Member Benefits': 'support/member-benefits/member-benefits.md'
      - 'Policies': 'support/policies/policies.md'
      - 'FAQ': 'support/faq/faq.md'
  - 'Programs':
      - 'Chapters':
          - 'Computer Society': 'chapters/cs/computers.md'
          - 'CAS/EDS Society Joint Chapter': 'chapters/cas-eds/cas-eds.md' 
      - 'Sub-Section Programs': 
          - 'Vizag Bay': 'sub-sections/vizag/vizag.md'
          - 'Guntur (Amaravathi)': 'sub-sections/guntur/guntur.md'
          - 'Ananthapur': 'sub-sections/ananthapur/ananthapur.md'
      - 'Industry Relations':
          - 'Industry Engagement': 'industry-relations/industry/engagement.md'
          - 'IEEE Standards': 'industry-relations/standards/participation.md'
      - 'Students':
          - 'Student Benefits': 'students/benefits/benefits.md'
          - 'Student Branches': 'students/branches/sbs.md'
      - 'Groups':
          - 'Young Professionals (YP)': 'affinity-groups/yp/yp.md'
          - 'Women in Engineering (WiE)': 'affinity-groups/yp/yp.md'
  - 'Chapters':
          - 'Computer Society': 'chapters/cs/computers.md'
          - 'CAS/EDS Society Joint Chapter': 'chapters/cas-eds/cas-eds.md' 
  - 'Dashboard':
          - 'Events': 'dashboard/events-summary.md'
          - 'Membership': 'dashboard/membership-summary.md'
          - 'Awards & Recognitions': 'dashboard/awards-recognitions-summary.md'
          - 'Alumni Network': 'dashboard/alumni-network-summary.md'
  - 'Contact': 'support/contact/ieeehyderabad.md'
  - 'More...':
      - 'Announcements':
          - 'Upcoming Events': 'announcements/upcoming-events/upcoming-events.md'
      - 'Get Involved': 'announcements/get-involved/get-involved.md'

  
