site_name: IEEE Hyderabad
site_description: 'IEEE Hyderabad Section. IEEE,Hyderabad,Computers,Communication,Signal Procesing,MTT,AP,EMC,Power Engieering,PES,PELS,IAS,CIS,GRSS,Vizag,Guntur,Anathapuram,Students'
theme:
    name: mkdocs
    custom_dir: ieeehyd_theme
extra_css: [extra.css]
google_analytics: ['UA-111776382-1', 'ieeehyderabad.org']
markdown_extensions:
    - smarty

pages:
    - 'Home': 'index.md'

    - 'Section': 
                - 'IEEE Hyderabad Section': 'section/section.md'
                - 'Future Directions Committee': 'section/future-directions/2018.md'
                - 'News Room': 'news-room/details.md'
                - 'Contact': 'support/contact/ieeehyderabad.md'
    - 'Sub-Sections': 
                - 'Vizag Bay': 'sub-sections/vizag/vizag.md'
                - 'Guntur (Amaravathi)': 'sub-sections/guntur/guntur.md'
                - 'Ananthapur': 'sub-sections/ananthapur/ananthapur.md'
    - 'Flagship Events':
                - 'Conferences': 'section/flagship-programs/conferences/conferences.md'
                - 'Faraday Memorial Lecture (FML)': 'section/flagship-programs/fml/fml.md'
                - 'Section Student Congress (SSC)': 'students/flagship-programs/programs.md'
                - 'Skill Connect': 'section/flagship-programs/skill-connect/skill-connect.md'
                
    - 'Chapters/AG':
                - 'CAS/EDS': 'chapters/cas-eds/cas-eds.md'
                - 'CIS/GRSS': 'chapters/cis-grss/cis-grss.md'
                - 'Computer Society': 'chapters/cs/computers.md'
                - 'ComSoc/SP': 'chapters/comsoc-sp/comsoc-sp.md'
                - 'Education Society': 'chapters/edusoc/edusoc.md'
                - 'MTT/AP/EMC': 'chapters/mtt-ap-emc/mtt-ap-emc.md'
                - 'PES/IAS/PELS': 'chapters/pes-ias-pels/pes-ias-pels.md'
                - 'Photonics': 'chapters/photonics/photonics.md'
                - 'TEMS': 'chapters/tems/tems.md'
                - 'Women in Engineering (WiE)': 'affinity-groups/wie/wie.md'
                - 'Young Professionals (YP)': 'affinity-groups/yp/yp.md'

    - 'Students':
                - 'Activites': 'students/students.md'
                - 'Student Branches': 'students/branches/sbs.md'
                - 'Events': 'students/events/details.md'
                - 'Benefits': 'students/benefits/benefits.md'
                - 'Opportunities': 'students/opportunities/jobs-internships.md'
                

    - 'More...':
        - 'News Room': 'news-room/details.md'
        - 'FAQ': 'support/faq/faq.md'
        - 'Content Instructions': 'support/faq/content-template.md'
        - 'Contact': 'support/contact/ieeehyderabad.md'

